from __future__ import annotations

from datetime import date, datetime

try:
    import yfinance as yf
except Exception:  # pragma: no cover
    yf = None

from src.models import (
    BenchmarkComparison,
    ConcentrationRisk,
    HealthCheckOutput,
    Observation,
    ObservationSeverity,
    Performance,
    UserProfile,
)

DISCLAIMER = (
    "This analysis is generated by an AI system and is for informational purposes only. "
    "It is not investment advice and does not constitute financial advice, investment recommendations, or a solicitation "
    "to buy or sell any security. Past performance is not indicative of future results. "
    "Please consult a certified financial advisor before making investment decisions."
)


def _years_since_oldest_position(user: UserProfile) -> float:
    dates = []
    for p in user.positions:
        if p.purchased_at:
            try:
                dates.append(datetime.fromisoformat(p.purchased_at).date())
            except ValueError:
                continue
    if not dates:
        return 1.0
    days = max((date.today() - min(dates)).days, 1)
    return days / 365.25


def run(user_profile: dict | UserProfile, query: str | None = None, llm=None) -> dict:
    profile = user_profile if isinstance(user_profile, UserProfile) else UserProfile(**user_profile)
    if not profile.positions:
        return HealthCheckOutput(
            mode="build",
            observations=[
                Observation(
                    severity=ObservationSeverity.INFO,
                    text="You have no holdings yet. Consider starting with a diversified ETF such as VTI or a target-date fund.",
                ),
                Observation(
                    severity=ObservationSeverity.INFO,
                    text="Before investing, build an emergency fund covering at least 3-6 months of expenses.",
                ),
            ],
            disclaimer=DISCLAIMER,
        ).model_dump()

    prices: dict[str, float] = {}
    unavailable: list[str] = []
    for position in profile.positions:
        ticker = position.ticker
        try:
            if yf is None:
                raise RuntimeError("yfinance unavailable")
            hist = yf.Ticker(ticker).history(period="5d", auto_adjust=True)
            price = float(hist["Close"].iloc[-1])
            prices[ticker] = price
        except Exception:
            unavailable.append(ticker)

    valid_positions = [p for p in profile.positions if p.ticker in prices and prices[p.ticker] > 0]
    if not valid_positions:
        return HealthCheckOutput(
            mode="monitor",
            observations=[
                Observation(
                    severity=ObservationSeverity.WARNING,
                    text="Live market data was unavailable for all holdings. Please try again shortly.",
                )
            ],
            disclaimer=DISCLAIMER,
        ).model_dump()

    total_value = sum(p.quantity * prices[p.ticker] for p in valid_positions)
    total_cost = sum(p.quantity * p.avg_cost for p in valid_positions) or 1e-9
    pos_values = sorted(
        ((p.ticker, p.quantity * prices[p.ticker]) for p in valid_positions),
        key=lambda item: item[1],
        reverse=True,
    )
    top_1_pct = (pos_values[0][1] / total_value) * 100 if total_value else 0.0
    top_3_pct = (sum(v for _, v in pos_values[:3]) / total_value) * 100 if total_value else 0.0
    flag = "high" if top_1_pct > 40 else "medium" if top_1_pct > 20 else "low"

    total_return_pct = ((total_value - total_cost) / total_cost) * 100
    years = _years_since_oldest_position(profile)
    annualized_return_pct = ((1 + total_return_pct / 100) ** (1 / years) - 1) * 100 if years > 0 else 0.0

    benchmark = None
    alpha_pct = None
    try:
        if yf is None:
            raise RuntimeError("yfinance unavailable")
        spy = yf.Ticker("SPY").history(period="1y", auto_adjust=True)
        spy_return_pct = ((float(spy["Close"].iloc[-1]) - float(spy["Close"].iloc[0])) / float(spy["Close"].iloc[0])) * 100
        alpha_pct = total_return_pct - spy_return_pct
        benchmark = BenchmarkComparison(
            benchmark="S&P 500",
            portfolio_return_pct=round(total_return_pct, 2),
            benchmark_return_pct=round(spy_return_pct, 2),
            alpha_pct=round(alpha_pct, 2),
        )
    except Exception:
        benchmark = None

    observations: list[Observation] = []
    if flag == "high":
        observations.append(
            Observation(
                severity=ObservationSeverity.WARNING,
                text=f"{round(top_1_pct, 1)}% of your portfolio is in {pos_values[0][0]}. This is highly concentrated.",
            )
        )
    if alpha_pct is not None:
        if alpha_pct >= 0:
            observations.append(
                Observation(
                    severity=ObservationSeverity.INFO,
                    text=f"You are outperforming the S&P 500 by {round(alpha_pct, 2)}% over the measured period.",
                )
            )
        else:
            observations.append(
                Observation(
                    severity=ObservationSeverity.WARNING,
                    text=f"You are underperforming the S&P 500 by {round(abs(alpha_pct), 2)}% over the measured period.",
                )
            )
    if unavailable:
        observations.append(
            Observation(
                severity=ObservationSeverity.INFO,
                text=f"Some holdings were skipped due to unavailable live data: {', '.join(sorted(set(unavailable)))}.",
            )
        )

    payload = HealthCheckOutput(
        mode="monitor",
        concentration_risk=ConcentrationRisk(
            top_position_pct=round(top_1_pct, 1),
            top_3_positions_pct=round(top_3_pct, 1),
            flag=flag,
        ),
        performance=Performance(
            total_return_pct=round(total_return_pct, 2),
            annualized_return_pct=round(annualized_return_pct, 2),
        ),
        benchmark_comparison=benchmark,
        observations=observations[:3],
        disclaimer=DISCLAIMER,
    )
    return payload.model_dump()
